import { COLORS, SIZES, FONTS, SHADOWS } from './theme';
import { ViewStyle, TextStyle } from 'react-native';

export const createStyles = (width: number) => ({
  // Layout
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  loadingContent: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SIZES.padding.lg,
  },
  loadingLogo: {
    fontSize: 80,
    marginBottom: SIZES.padding.lg,
  },
  loadingText: {
    fontSize: SIZES.base,
    color: COLORS.textSecondary,
    marginTop: SIZES.padding.md,
    fontFamily: FONTS.primary,
  },

  // Auth Screen
  authContent: {
    flex: 1,
    justifyContent: 'center' as const,
    padding: SIZES.padding.xl,
  },
  authLogo: {
    fontSize: 80,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.lg,
  },
  authTitle: {
    fontSize: SIZES.xxxl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  authSubtitle: {
    fontSize: SIZES.base,
    color: COLORS.textSecondary,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.xl,
    fontFamily: FONTS.primary,
  },
  googleBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.textLight,
    borderRadius: SIZES.radius.md,
    paddingVertical: SIZES.padding.md,
    marginBottom: SIZES.padding.lg,
    ...SHADOWS.light,
  },
  googleIcon: {
    fontSize: SIZES.lg,
    marginRight: SIZES.padding.sm,
  },
  googleText: {
    fontSize: SIZES.base,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  divider: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: SIZES.padding.lg,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.textLight,
  },
  dividerText: {
    marginHorizontal: SIZES.padding.md,
    color: COLORS.textSecondary,
    fontSize: SIZES.sm,
    fontFamily: FONTS.primary,
  },
  toggleAuthText: {
    color: COLORS.primary,
    textAlign: 'center' as const,
    marginTop: SIZES.padding.lg,
    fontSize: SIZES.sm,
    fontFamily: FONTS.primary,
  },
  demoBtn: {
    backgroundColor: COLORS.background,
    paddingVertical: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    marginTop: SIZES.padding.lg,
    borderWidth: 1,
    borderColor: COLORS.textLight,
    ...SHADOWS.light,
  },
  demoBtnText: {
    color: COLORS.textSecondary,
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    fontFamily: FONTS.primary,
  },

  // Welcome Screen
  welcomeContent: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: SIZES.padding.xl,
  },
  logo: {
    fontSize: 100,
    marginBottom: SIZES.padding.lg,
  },
  appName: {
    fontSize: SIZES.huge,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  tagline: {
    fontSize: SIZES.base,
    color: COLORS.textSecondary,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.xl,
    fontFamily: FONTS.primary,
  },
  featureList: {
    width: '100%' as const,
    marginBottom: SIZES.padding.xl,
  },
  featureRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: SIZES.padding.md,
    backgroundColor: COLORS.surface,
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
    ...SHADOWS.light,
  },
  featureIcon: {
    fontSize: SIZES.lg,
    marginRight: SIZES.padding.md,
  },
  featureText: {
    fontSize: SIZES.sm,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },

  // Onboarding
  onboardingHeader: {
    padding: SIZES.padding.lg,
    paddingBottom: SIZES.padding.md,
  },
  stepText: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  progressBar: {
    height: 4,
    backgroundColor: COLORS.textLight,
    borderRadius: 2,
    overflow: 'hidden' as const,
  },
  progressFill: {
    height: '100%' as const,
    backgroundColor: COLORS.primary,
    borderRadius: 2,
  },
  stepContent: {
    padding: SIZES.padding.lg,
  },
  stepTitle: {
    fontSize: SIZES.xl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    marginBottom: SIZES.padding.xl,
    fontFamily: FONTS.primary,
  },
  inputLabel: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.text,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.textLight,
    borderRadius: SIZES.radius.md,
    padding: SIZES.padding.md,
    fontSize: SIZES.base,
    backgroundColor: COLORS.surface,
    marginBottom: SIZES.padding.lg,
    fontFamily: FONTS.primary,
    ...SHADOWS.light,
  },
  optionRow: {
    flexDirection: 'row' as const,
    marginBottom: SIZES.padding.lg,
  },
  optionBtn: {
    flex: 1,
    padding: SIZES.padding.md,
    borderWidth: 1,
    borderColor: COLORS.textLight,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    marginRight: SIZES.padding.sm,
    backgroundColor: COLORS.surface,
    fontFamily: FONTS.primary,
    ...SHADOWS.light,
  },
  optionBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  optionBtnText: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  optionBtnTextActive: {
    color: COLORS.surface,
    fontWeight: '700' as const,
  },
  optionText: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  optionTextActive: {
    color: COLORS.surface,
    fontWeight: '700' as const,
  },
  tabIconActive: {
    transform: [{ scale: 1.15 }],
  },
  primaryBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: SIZES.padding.md,
    paddingHorizontal: SIZES.padding.xl,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    ...SHADOWS.medium,
  },
  primaryBtnText: {
    color: COLORS.surface,
    fontSize: SIZES.base,
    fontWeight: '700' as const,
    fontFamily: FONTS.primary,
  },
  outlineBtn: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    paddingVertical: SIZES.padding.md,
    paddingHorizontal: SIZES.padding.xl,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    backgroundColor: COLORS.surface,
  },
  outlineBtnText: {
    color: COLORS.primary,
    fontSize: SIZES.base,
    fontWeight: '600' as const,
    fontFamily: FONTS.primary,
  },

  // Main App
  header: {
    padding: SIZES.padding.lg,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.textLight,
    ...SHADOWS.light,
  },
  headerTitle: {
    fontSize: SIZES.xxl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    fontFamily: FONTS.primary,
  },
  headerSubtitle: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginTop: SIZES.padding.xs,
    fontFamily: FONTS.primary,
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.lg,
    padding: SIZES.padding.lg,
    marginBottom: SIZES.padding.md,
    ...SHADOWS.medium,
  },
  cardTitle: {
    fontSize: SIZES.lg,
    fontWeight: '600' as const,
    color: COLORS.primaryDark,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  cardSubtitle: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },

  // Nutrition
  nutritionGrid: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    marginBottom: SIZES.padding.lg,
  },
  nutritionItem: {
    alignItems: 'center' as const,
    backgroundColor: COLORS.surface,
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
    flex: 1,
    marginHorizontal: SIZES.padding.xs,
    ...SHADOWS.light,
  },
  nutritionValue: {
    fontSize: SIZES.lg,
    fontWeight: '700' as const,
    color: COLORS.primary,
    fontFamily: FONTS.primary,
  },
  nutritionLabel: {
    fontSize: SIZES.xs,
    color: COLORS.textSecondary,
    marginTop: SIZES.padding.xs,
    fontFamily: FONTS.primary,
  },
  progressRing: {
    width: 120,
    height: 120,
    alignSelf: 'center' as const,
    marginBottom: SIZES.padding.lg,
  },

  // Meals
  mealCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.lg,
    padding: SIZES.padding.lg,
    marginBottom: SIZES.padding.md,
    ...SHADOWS.medium,
  },
  mealHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: SIZES.padding.md,
  },
  mealTitle: {
    fontSize: SIZES.lg,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  mealEmoji: {
    fontSize: SIZES.xxl,
  },
  mealInfo: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  mealActions: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
  },
  actionBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: SIZES.padding.sm,
    paddingHorizontal: SIZES.padding.md,
    borderRadius: SIZES.radius.sm,
    alignItems: 'center' as const,
  },
  actionBtnText: {
    color: COLORS.surface,
    fontSize: SIZES.xs,
    fontWeight: '600' as const,
    fontFamily: FONTS.primary,
  },

  // Tab Bar
  tabBar: {
    flexDirection: 'row' as const,
    backgroundColor: COLORS.surface,
    borderTopWidth: 1,
    borderTopColor: COLORS.textLight,
    paddingBottom: SIZES.padding.sm,
    ...SHADOWS.light,
  },
  tabBtn: {
    flex: 1,
    alignItems: 'center' as const,
    paddingVertical: SIZES.padding.sm,
  },
  tabBtnActive: {
    borderTopWidth: 2,
    borderTopColor: COLORS.primary,
  },
  tabIcon: {
    fontSize: SIZES.lg,
    marginBottom: SIZES.padding.xs,
  },
  tabLabel: {
    fontSize: SIZES.xs,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  tabLabelActive: {
    color: COLORS.primary,
    fontWeight: '600' as const,
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end' as const,
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderTopLeftRadius: SIZES.radius.xl,
    borderTopRightRadius: SIZES.radius.xl,
    padding: SIZES.padding.xl,
    maxHeight: '85%' as const,
  },
  modalEmoji: {
    fontSize: 60,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.lg,
  },
  modalTitle: {
    fontSize: SIZES.xxl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    textAlign: 'center' as const,
    fontFamily: FONTS.primary,
  },
  modalDesc: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    textAlign: 'center' as const,
    marginBottom: SIZES.padding.lg,
    fontFamily: FONTS.primary,
  },

  // Profile
  profileHeader: {
    alignItems: 'center' as const,
    marginBottom: SIZES.padding.xl,
  },
  avatar: {
    width: 80,
    height: 80,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 40,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: SIZES.padding.md,
    ...SHADOWS.medium,
  },
  avatarText: {
    fontSize: 40,
  },
  profileName: {
    fontSize: SIZES.xxl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    fontFamily: FONTS.primary,
  },
  profileGoal: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  targetRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    paddingVertical: SIZES.padding.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.textLight,
  },
  targetLabel: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  targetValue: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  profileInfo: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },

  // Additional styles for App.tsx
  greeting: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  userName: {
    fontSize: SIZES.xl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    fontFamily: FONTS.primary,
  },
  aiButton: {
    backgroundColor: COLORS.primary,
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    ...SHADOWS.medium,
  },
  aiButtonText: {
    fontSize: 20,
    color: COLORS.surface,
  },
  cardHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: SIZES.padding.md,
  },
  addMealBtn: {
    color: COLORS.primary,
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    fontFamily: FONTS.primary,
  },
  generateBtn: {
    flexDirection: 'row' as const,
    backgroundColor: COLORS.primary,
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: SIZES.padding.lg,
    ...SHADOWS.medium,
  },
  generateBtnIcon: {
    fontSize: SIZES.lg,
    marginRight: SIZES.padding.sm,
  },
  generateBtnText: {
    color: COLORS.surface,
    fontSize: SIZES.base,
    fontWeight: '700' as const,
    fontFamily: FONTS.primary,
  },
  screenTitle: {
    fontSize: SIZES.xxl,
    fontWeight: '700' as const,
    color: COLORS.primaryDark,
    marginBottom: SIZES.padding.md,
    fontFamily: FONTS.primary,
  },
  screenSubtitle: {
    fontSize: SIZES.base,
    color: COLORS.textSecondary,
    marginBottom: SIZES.padding.lg,
    fontFamily: FONTS.primary,
  },
  dayCard: {
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    padding: SIZES.padding.md,
    marginBottom: SIZES.padding.sm,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    ...SHADOWS.light,
  },
  dayTitle: {
    fontSize: SIZES.base,
    fontWeight: '700' as const,
    color: COLORS.primary,
    width: 50,
    fontFamily: FONTS.primary,
  },
  dayMeals: {
    flex: 1,
  },
  miniMeal: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginBottom: 2,
    fontFamily: FONTS.primary,
  },
  recipeCard: {
    flexDirection: 'row' as const,
    backgroundColor: COLORS.surface,
    borderRadius: SIZES.radius.md,
    padding: SIZES.padding.md,
    marginBottom: SIZES.padding.sm,
    alignItems: 'center' as const,
    ...SHADOWS.light,
  },
  recipeEmoji: {
    fontSize: 40,
    marginRight: SIZES.padding.md,
  },
  recipeInfo: {
    flex: 1,
  },
  recipeName: {
    fontSize: SIZES.base,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  recipeMeta: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginTop: 2,
    fontFamily: FONTS.primary,
  },
  tagRow: {
    flexDirection: 'row' as const,
    marginTop: 6,
    flexWrap: 'wrap' as const,
  },
  tag: {
    backgroundColor: COLORS.surface,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginRight: 6,
  },
  tagText: {
    fontSize: 10,
    color: COLORS.primary,
    fontWeight: '500' as const,
    fontFamily: FONTS.primary,
  },
  navButtons: {
    flexDirection: 'row' as const,
    marginTop: SIZES.padding.lg,
    marginBottom: 40,
  },
  goalCard: {
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
    borderWidth: 1,
    borderColor: COLORS.textLight,
    marginBottom: SIZES.padding.md,
    backgroundColor: COLORS.surface,
    ...SHADOWS.light,
  },
  goalCardActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.surface,
  },
  goalLabel: {
    fontSize: SIZES.base,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  goalDesc: {
    fontSize: SIZES.sm,
    color: COLORS.textSecondary,
    marginTop: 4,
    fontFamily: FONTS.primary,
  },
  checkItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.sm,
    backgroundColor: COLORS.surface,
    marginBottom: SIZES.padding.sm,
    borderWidth: 1,
    borderColor: COLORS.textLight,
    ...SHADOWS.light,
  },
  checkItemActive: {
    backgroundColor: COLORS.surface,
    borderColor: COLORS.primary,
  },
  checkIcon: {
    fontSize: 18,
    marginRight: SIZES.padding.md,
  },
  checkText: {
    fontSize: SIZES.sm,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  closeBtn: {
    position: 'absolute' as const,
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.textLight,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  closeBtnText: {
    fontSize: 18,
    color: COLORS.textSecondary,
  },
  mealTypeGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 12,
    marginVertical: SIZES.padding.lg,
  },
  mealTypeBtn: {
    width: (width - 80) / 2,
    backgroundColor: COLORS.surface,
    padding: SIZES.padding.lg,
    borderRadius: SIZES.radius.md,
    alignItems: 'center' as const,
    ...SHADOWS.light,
  },
  mealTypeIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  mealTypeText: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.primary,
    fontFamily: FONTS.primary,
  },
  nutritionCircle: {
    width: 65,
    height: 65,
    borderRadius: 32,
    borderWidth: 4,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: COLORS.surface,
  },
  nutritionUnit: {
    fontSize: 9,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  nutritionTarget: {
    fontSize: 10,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  mealTime: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontWeight: '500' as const,
    fontFamily: FONTS.primary,
  },
  mealName: {
    fontSize: SIZES.sm,
    fontWeight: '600' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  mealCals: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontFamily: FONTS.primary,
  },
  logBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.surface,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    ...SHADOWS.light,
  },
  logBtnText: {
    fontSize: 20,
    color: COLORS.primary,
    fontWeight: '700' as const,
  },
  macroRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-around' as const,
    marginVertical: SIZES.padding.lg,
    backgroundColor: COLORS.background,
    padding: SIZES.padding.md,
    borderRadius: SIZES.radius.md,
  },
  macroItem: {
    alignItems: 'center' as const,
  },
  macroValue: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: COLORS.text,
    fontFamily: FONTS.primary,
  },
  macroLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    marginTop: 4,
    fontFamily: FONTS.primary,
  },
  sectionTitle: {
    fontSize: SIZES.base,
    fontWeight: '600' as const,
    color: COLORS.primaryDark,
    marginTop: SIZES.padding.lg,
    marginBottom: SIZES.padding.sm,
    fontFamily: FONTS.primary,
  },
  listItem: {
    fontSize: SIZES.sm,
    color: COLORS.text,
    marginBottom: 6,
    lineHeight: 20,
    fontFamily: FONTS.primary,
  },
});

export default createStyles;
