import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { AuthStackParamList } from '../../navigation/types';
import { textStyles, colors } from '../../constants/theme';

type NavigationProp = NativeStackNavigationProp<AuthStackParamList, 'Welcome'>;

const WelcomeScreen: React.FC = () => {
  const navigation = useNavigation<NavigationProp>();
  
  const features = [
    { icon: '🤖', title: 'AI-Powered Plans', desc: 'Personalized meal plans generated by AI' },
    { icon: '📊', title: 'Track Nutrition', desc: 'Monitor your daily intake effortlessly' },
    { icon: '🛒', title: 'Smart Shopping', desc: 'Auto-generated shopping lists' },
    { icon: '🎯', title: 'Reach Goals', desc: 'Achieve your health objectives' },
  ];
  
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.content}>
        <View style={styles.header}>
          <Text style={styles.logo}>🥗</Text>
          <Text style={styles.title}>NutriPlan</Text>
          <Text style={styles.subtitle}>
            Your personal AI nutritionist for healthier eating
          </Text>
        </View>
        
        <View style={styles.features}>
          {features.map((feature, index) => (
            <View key={index} style={styles.featureItem}>
              <Text style={styles.featureIcon}>{feature.icon}</Text>
              <View style={styles.featureText}>
                <Text style={styles.featureTitle}>{feature.title}</Text>
                <Text style={styles.featureDesc}>{feature.desc}</Text>
              </View>
            </View>
          ))}
        </View>
        
        <View style={styles.footer}>
          <TouchableOpacity
            style={styles.button}
            onPress={() => navigation.navigate('SignIn')}
          >
            <Text style={styles.buttonText}>Get Started</Text>
          </TouchableOpacity>
          <Text style={styles.terms}>
            By continuing, you agree to our Terms of Service and Privacy Policy
          </Text>
        </View>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    flex: 1,
    padding: 24,
    justifyContent: 'space-between',
  },
  header: {
    alignItems: 'center',
    marginTop: 32,
  },
  logo: {
    fontSize: 64,
    marginBottom: 16,
  },
  title: {
    ...textStyles.displaySmall,
    color: colors.primary,
    marginBottom: 8,
  },
  subtitle: {
    ...textStyles.body,
    color: '#757575',
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  features: {
    marginVertical: 32,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    backgroundColor: colors.primaryPale,
    padding: 16,
    borderRadius: 12,
  },
  featureIcon: {
    fontSize: 32,
    marginRight: 16,
  },
  featureText: {
    flex: 1,
  },
  featureTitle: {
    ...textStyles.body,
    fontWeight: '600',
    color: colors.primaryDark,
    marginBottom: 2,
  },
  featureDesc: {
    ...textStyles.bodySmall,
    color: '#757575',
  },
  footer: {
    marginBottom: 16,
  },
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
  },
  buttonText: {
    ...textStyles.buttonLarge,
    color: '#FFFFFF',
  },
  terms: {
    ...textStyles.caption,
    color: '#9E9E9E',
    textAlign: 'center',
    marginTop: 16,
    paddingHorizontal: 24,
  },
});

export default WelcomeScreen;
